Check dictionary is not already added to prevent error
System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Articulate.UmbracoEventHandler.ServerVariablesParser_Parsing(Object sender, Dictionary`2 e) in x:\Projects\Articulate\Articulate.Project\Articulate\UmbracoEventHandler.cs:line 192